### ISSUE TITLE
CFBundleIdentifier, Does Not Exist

### ISSUE THREAD

**Issue by ShawnDeveloper** [codingplayboy/reactjs#4]
你好，run-ios的时候一直报下面的错误怎么办
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Install\ Third\ Party /Users/jxtr/Downloads/reactjs-master\ 2/react-native/fuc/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/fuc.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
lstat of /Users/jxtr/Downloads/reactjs-master 2/react-native/fuc/ios/build/Build/Products/Debug-iphonesimulator/fuc.app failed: No such file or directory
No such file or directory
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/fuc.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by ShawnDeveloper** [comment]
重建项目后解决了

**Comment by emthink** [comment]
@ShawnDeveloper 抱歉，才看到哈，这个你创建的项目目录必须和我上传的一样，因为这是编译后的代码，里面已经包含对应的目录关系，所以需要存在对应目录。
如果想创建自定义项目，就需要自己创建一个react-native目录然后把src目录下代码迁移过去。
