### ISSUE TITLE
redux state和dom state可以混着用吗

### ISSUE THREAD

**Issue by objHua** [codingplayboy/reactjs#6]
看到loginScreen里，输入框的文字直接用setState方法来更新，可以这样做吗，redux小白，求解惑

**Comment by emthink** [comment]
`输入框的文字直接用setState方法来更新，可以这样做吗`

-当然可以。

你问的应该是redux state和component state是否可以混用吧，可以的，但是他们有一些区别，redux state一般是维护多组件公用状态，而组件state一般维护组件自己使用的状态或其子组件使用的状态。

通常，某一组件内独立使用的状态就放在该组件内，而若外部需要访问该状态，则将该状态向上抽调至上级组件以使其他组件能访问到该状态；若抽象至模块根组件依然不能覆盖所以使用情况，则将该状态抽象至redux state维护，在需要使用该状态的模块根组件，以prop形式注入该状态值。

**Comment by objHua** [comment]
明白了，谢谢
